prooph_event_store:
    stores:
        moodvalue_store:
            adapter: prooph_event_store.doctrine_adapter.moodvalue_store
            repositories:
                user_repository:
                    repository_class: MoodValue\Infrastructure\Repository\EventStoreUserRepository
                    aggregate_type: MoodValue\Model\User\User
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
                event_repository:
                    repository_class: MoodValue\Infrastructure\Repository\EventStoreEventRepository
                    aggregate_type: MoodValue\Model\Event\Event
                    aggregate_translator: prooph_event_sourcing.aggregate_translator

services:
    prooph_event_store.doctrine_adapter.moodvalue_store:
        class: Prooph\EventStore\Adapter\Doctrine\DoctrineEventStoreAdapter
        arguments:
            - '@database_connection'
            - '@prooph_event_store.message_factory'
            - '@prooph_event_store.message_converter'
            - '@prooph_event_store.payload_serializer'
            - '%prooph_event_store.stream_table_map%'

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

    prooph_event_store_bus_bridge.transaction_manager:
        class: Prooph\EventStoreBusBridge\TransactionManager
        tags:
            - { name: 'prooph_event_store.moodvalue_store.plugin' }

    prooph_event_store_bus_bridge.moodvalue_event_publisher:
        class: Prooph\EventStoreBusBridge\EventPublisher
        arguments: ['@prooph_service_bus.moodvalue_event_bus']
        tags:
            - { name: 'prooph_event_store.moodvalue_store.plugin' }
