services:
    user.repository:
        alias: user.in_file.repository

    user.in_memory.repository:
        class: MoodValue\Infrastructure\Repository\UserInMemoryRepository
        public: false


    user.in_file.repository:
        class: MoodValue\Infrastructure\Repository\UserInFileRepository
        public: false
        arguments:
            - %kernel.root_dir%
