services:
    moodvalue.register_user_handler:
        class: MoodValue\Model\User\Handler\RegisterUserHandler
        arguments: ['@user_repository']

    moodvalue.add_device_token_to_user_handler:
        class: MoodValue\Model\User\Handler\AddDeviceTokenToUserHandler
        arguments: ['@user_repository']

    moodvalue.add_event_handler:
        class: MoodValue\Model\Event\Handler\AddEventHandler
        arguments: ['@event_repository']

    moodvalue.join_event_handler:
        class: MoodValue\Model\User\Handler\JoinEventHandler
        arguments: ['@user_repository']
